### ISSUE TITLE
MAG:METABAT2_BINNING:METABAT2 Fails with missing fasta 

### ISSUE THREAD

**Issue by vpeddu** [nf-core/mag#211] opened 2021-06-10 21:30 UTC
## Description of the bug
Running MAG on paired files produces the following error:
`Missing output file(s) MetaBAT2/*.fa  expected by process MAG:METABAT2_BINNING:METABAT2 (MEGAHIT-BioIVT_panc9_2-5_S91)`

## Steps to reproduce
Command ran: 
```nextflow run nf-core/mag \
		 -profile docker \
		 --input './*_R{1,2}_001.fastq.gz' \
		 --outdir MAG_testrun/ \
		 --kraken2_db /refs/metagenomics/kraken2/k2_standard_16gb_20210517.tar.gz.1 \
		 -c /private/home/vpeddu/nextflow.config \
		 -with-tower \
		 -resume \
		 -bg \
		 --gtdb 'https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/auxillary_files/gtdbtk_data.tar.gz'
```

## Expected behaviour
Pipeline runs to completion

## Log files

Have you provided the following extra information/files:
.command.log: 
```
-bash-4.2$ cat /private/groups/kimlab/vikas/metagenomics/testing/work/93/3281c15a3ba725cbfcbedf9a6bd580/.command.log 
Output depth matrix to depth.txt
jgi_summarize_bam_contig_depths 2.15 (Bioconda) 2020-07-03T13:02:15
Output matrix to depth.txt
0: Opening bam: MEGAHIT-BioIVT_panc9_2-5_S91-BioIVT_panc9_2-5_S91.bam
1: Opening bam: MEGAHIT-BioIVT_panc9_2-5_S91-BioIVT_panc8_2-5_S90.bam
Processing bam files
Thread 0 finished: MEGAHIT-BioIVT_panc9_2-5_S91-BioIVT_panc9_2-5_S91.bam with 4078894 reads and 2024980 readsWellMapped
Thread 1 finished: MEGAHIT-BioIVT_panc9_2-5_S91-BioIVT_panc8_2-5_S90.bam with 7212422 reads and 5207907 readsWellMapped
Creating depth matrix file: depth.txt
Closing most bam files
Closing last bam file
Finished
MetaBAT 2 (2.15 (Bioconda)) using minContig 1500, minCV 1.0, minCVSum 1.0, maxP 95%, minS 60, maxEdges 200 and minClsSize 200000. with random seed=1
0 bins (0 bases in total) formed.
write MetaBAT2/MEGAHIT-BioIVT_panc9_2-5_S91.unbinned.pooled.fa
write MetaBAT2/MEGAHIT-BioIVT_panc9_2-5_S91.unbinned.remaining.fa
```

## System

- Hardware: HPC
- Executor: local
- OS: Linux
- Version 3.10.0-862.6.3.el7.x86_64

## Nextflow Installation

- Version: nextflow version 21.04.1.5556

## Container engine

- Engine: docker

## Additional context

Not sure why this is failing- it consistently happens across multiple types of files. The pipeline doesn't proceed after it fails

**Comment by d4straub** [comment] 2021-06-11 07:13
Hi there, your log shows:

> 0 bins (0 bases in total) formed.

This seems pretty clear to me. You have no bins/MAGs produced. This means the pipeline fails at that point. To conclude WHY no bins are found, more info would be needed. E.g. how deep you sequenced, the duplication level, the environment you sampled, the QUAST results of the assembly etc.

At this point I would say this isn't a bug but caused by the data. But I cannot be sure of course.

**Comment by d4straub** [comment] 2021-06-29 07:24
Closing this because there is no reply. Feel free to open a new issue in case you encounter another problem!

**Closed by d4straub** 2021-06-29 07:24 UTC
Labels: bug
