### ISSUE TITLE
Busco failed with test data

### ISSUE THREAD

**Issue by xiaoli-dong** [nf-core/mag#303] opened 2022-05-19 16:35 UTC
I was testing mag pipeline with the test data. It failed at running busco. I also checked with busco 5.3.2. The errors are the same:

2022-05-19 10:22:32 CRITICAL:   Unhandled exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/busco/BuscoRunner.py", line 138, in run
    self.runner.run_analysis()
  File "/usr/local/lib/python3.9/site-packages/busco/BuscoRunner.py", line 420, in run_analysis
    self.analysis.run_analysis()
  File "/usr/local/lib/python3.9/site-packages/busco/analysis/GenomeAnalysis.py", line 81, in run_analysis
    self._run_prodigal()
  File "/usr/local/lib/python3.9/site-packages/busco/BuscoLogger.py", line 62, in wrapped_func
    self.retval = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/busco/analysis/GenomeAnalysis.py", line 112, in _run_prodigal
    self.prodigal_runner.run()
  File "/usr/local/lib/python3.9/site-packages/busco/busco_tools/prodigal.py", line 137, in run
    self.run_jobs()
  File "/usr/local/lib/python3.9/site-packages/busco/busco_tools/Toolset.py", line 198, in run_jobs
    self.cpus, initializer=type(self).init_globals, initargs=(Value("i", 0),)
  File "/usr/local/lib/python3.9/multiprocessing/context.py", line 135, in Value
    return Value(typecode_or_type, *args, lock=lock,
  File "/usr/local/lib/python3.9/multiprocessing/sharedctypes.py", line 74, in Value
    obj = RawValue(typecode_or_type, *args)
  File "/usr/local/lib/python3.9/multiprocessing/sharedctypes.py", line 49, in RawValue
    obj = _new_value(type_)
  File "/usr/local/lib/python3.9/multiprocessing/sharedctypes.py", line 41, in _new_value
    wrapper = heap.BufferWrapper(size)
  File "/usr/local/lib/python3.9/multiprocessing/heap.py", line 331, in __init__
    block = BufferWrapper._heap.malloc(size)
  File "/usr/local/lib/python3.9/multiprocessing/heap.py", line 309, in malloc
    (arena, start, stop) = self._malloc(size)
  File "/usr/local/lib/python3.9/multiprocessing/heap.py", line 192, in _malloc
    return self._new_arena(size)
  File "/usr/local/lib/python3.9/multiprocessing/heap.py", line 166, in _new_arena
    arena = Arena(length)
  File "/usr/local/lib/python3.9/multiprocessing/heap.py", line 85, in __init__
    dir=self._choose_dir(size))
  File "/usr/local/lib/python3.9/multiprocessing/heap.py", line 95, in _choose_dir
    st = os.statvfs(d)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm'

**Comment by d4straub** [comment] 2022-05-20 08:52
> I was testing mag pipeline with the test data.

Good choice, this test works on any properly setup computational resource. When the test fails, its very likely that the problem is at the users end, most likely an issue with the setup of the compute resource.

> FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm'

Looks like a possible permission clash or setup of the conda/docker/singularity/whatever-you-chose.

I'd like to highlight that the bug report form (that you delierately ignored?!)) is not there for amusement but for collecting relevent information. Because that information is not available here, I have no grounds for any further speculation or possible solution.

**Comment by d4straub** [comment] 2022-05-20 08:56
> I was testing mag pipeline with the test data.

Good choice, this test works on any properly setup computational resource. When the test fails, its very likely that the problem is at the users end, most likely an issue with the setup of the compute resource.

> FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm'

Looks like a possible permission clash or setup of the conda/docker/singularity/whatever-you-chose.

I'd like to highlight that the bug report form (that you delierately ignored?!)) is not there for amusement but for collecting relevent information. Because that information is not available here, I have no grounds for any further speculation or possible solution.

**Comment by skrakau** [comment] 2022-06-01 15:42
Since we cannot help currently due to missing information I will close this issue. Feel free to open a new issue with the relevant information in case this problem persists.

**Closed by skrakau** 2022-06-01 15:42 UTC
Labels: bug
